spring: 
  jpa: 
    hibernate: 
      ddl-auto: update
  datasource: 
    url: jdbc:postgresql://localhost:5432/hotel
    username: postgres
    password: 7083
    driver-class-name: org.postgresql.Driver
  mvc: 
    view:
      prefix: /WEB-INF/
      suffix: .jsp